const mongoose = require('mongoose');

const deviceSchema = new mongoose.Schema({
  MANUFACTURER: String,
  BRAND: String,
  MODEL: String,
  PRODUCT: String,
  PLATFORM: String,
  API: String,
  KERNEL: String,
  SOC: String,
  RESOLUTION: String,
  TOUCHSCREEN: String,
  TOUCHSCREEN_KEY: String,
  CAMERA: String,
  LENS: String,
  ACCELEROMETER: String,
  ALSPS: String,
  MAGNETOMETER: String,
  GYROSCOPE: String,
  CHARGER: String,
  PMIC: String,
  OTHER: String,
  CPU: String,
  CORES: String,
  FAMILY: String,
  CLUSTERS: String,
  CLOCK_SPEED: String,
  REVISION: String,
  TECHPROCESS: String,
  GPU_VENDOR: String,
  GPU_MODEL: String,
  GPU_CLOCK: String,
  GPU_VERSION: String,
  RAM: String,
  FLASH: String,
  FLASH_SIZE: String,
  NFC: String,
  AUDIO: String,
  FINGERPRINT_SENSOR: String,
  API_LEVEL: Number, 
  VERSION: String,
  tacs: Array
});
module.exports = mongoose.model('Device', deviceSchema);